import { expect } from 'vitest';
import { transpileSource } from '../src/transpiler.js';

/**
 * Normalize whitespace for comparison:
 * - Trim leading/trailing whitespace
 * - Normalize line endings to \n
 * - Remove trailing whitespace from each line
 */
export function normalize(code: string): string {
  return code
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map(line => line.trimEnd())
    .join('\n')
    .trim();
}

/**
 * Transpile TypeScript source to C#
 */
export function transpile(tsSource: string, config?: Record<string, unknown>): string {
  return transpileSource(tsSource, 'test.ts', config);
}

/**
 * Assert that TypeScript input transpiles to expected C# output
 */
export function expectCSharp(tsInput: string, expectedCs: string): void {
  const result = transpile(tsInput);
  expect(normalize(result)).toBe(normalize(expectedCs));
}

/**
 * Assert that TypeScript input transpiles to expected C# output with custom config
 */
export function expectCSharpWithConfig(
  tsInput: string, 
  expectedCs: string, 
  config: Record<string, unknown>
): void {
  const result = transpile(tsInput, config);
  expect(normalize(result)).toBe(normalize(expectedCs));
}

/**
 * The auto-generated header comment added to all C# files
 */
export const GENERATED_HEADER = `// <auto-generated>
//     This file was generated by ts2cs-transpiler. Do not edit manually.
// </auto-generated>`;

